--v7.3 Final
CREATE TABLE BenhNhan (    
    ID_BenhNhan SERIAL NOT NULL,
    HoVaTen TEXT NOT NULL,	
    GioiTinh CHAR(1) NOT NULL,
    NgaySinh DATE NOT NULL,	
    SDT VARCHAR(11) NOT NULL,
    ID_BHYT VARCHAR(6), --Minh hoa
    ThuocDiUng TEXT[],
    BenhLiDacBiet TEXT[],
    PRIMARY KEY (ID_BenhNhan)
);

CREATE TABLE Khoa (
    ID_Khoa SERIAL NOT NULL,
    TenKhoa TEXT NOT NULL,
    PRIMARY KEY (ID_Khoa)
);

CREATE TABLE BacSi (
    ID_BacSi SERIAL NOT NULL,
    HoVaTen TEXT NOT NULL,
    SDT CHAR(11) NOT NULL,
    GioiTinh CHAR(1) NOT NULL,
    NgaySinh DATE NOT NULL,
    ChucVu TEXT NOT NULL,
    ID_Khoa INT NOT NULL,
    PRIMARY KEY (ID_BacSi),
    FOREIGN KEY (ID_Khoa) REFERENCES Khoa(ID_Khoa)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE HoSoBenhAn (
    ID_HS SERIAL NOT NULL,
    ID_BenhNhan INT NOT NULL,
	ID_Bacsi INT NOT NULL,
    NgayKham DATE NOT NULL,
    HuyetAp INT NOT NULL,
    NhietDo NUMERIC NOT NULL,
    TinhTrangHienTai TEXT NOT NULL,    
    ChanDoan TEXT[],
    Thuoc TEXT[],
    GhiChu TEXT,
    LanTruoc_ID_HS INT UNIQUE,
    PRIMARY KEY (ID_HS),
    FOREIGN KEY (ID_BacSi) REFERENCES BacSi(ID_BacSi)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    FOREIGN KEY (ID_BenhNhan) REFERENCES BenhNhan(ID_BenhNhan)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    FOREIGN KEY (LanTruoc_ID_HS) REFERENCES HoSoBenhAn(ID_HS)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE XetNghiem (
    ID_XN SERIAL NOT NULL,
    ID_HS INT NOT NULL,
    ID_BacSiXN INT,
    ThoiGian TIMESTAMP NOT NULL,
    GhiChu TEXT,
    PRIMARY KEY (ID_XN),
    FOREIGN KEY (ID_HS) REFERENCES HoSoBenhAn(ID_HS)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    FOREIGN KEY (ID_BacSiXN) REFERENCES BacSi(ID_BacSi)
    ON UPDATE CASCADE
    ON DELETE SET NULL
);

CREATE TABLE NuocTieu 
(
    ID_XN INT NOT NULL,
    Glucose NUMERIC NOT NULL,
    pH NUMERIC NOT NULL,
    FOREIGN KEY (ID_XN) REFERENCES XetNghiem(ID_XN)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE Mau (
    ID_XN INT NOT NULL,
    Glucose NUMERIC NOT NULL,
    NhomMau VARCHAR(3) NOT NULL,
    SLHongCau NUMERIC NOT NULL,
    FOREIGN KEY (ID_XN) REFERENCES XetNghiem(ID_XN)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE MauThamChieu
(
    SLHongCauMin NUMERIC NOT NULL,
    SLHongCauMax NUMERIC NOT NULL,
    SLHongCauDV VARCHAR NOT NULL,
    GlucoseMin NUMERIC NOT NULL,
    GlucoseMax NUMERIC NOT NULL,
    GlucoseDV VARCHAR NOT NULL
);

CREATE TABLE NuocTieuThamChieu
(
    pHMin NUMERIC NOT NULL,
    pHMax NUMERIC NOT NULL,
    GlucoseMin NUMERIC NOT NULL,
    GlucoseMax NUMERIC NOT NULL,
    GlucoseDV VARCHAR NOT NULL
);
